// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzynyviczaotqlinktpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6eW55dmljemFvdHFsaW5rdHBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NDYyMTAsImV4cCI6MjA3MzQyMjIxMH0.5wSJaVv792yWb7jrBkJ4AcMMJwioYYNsYyjH-pxbGJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});